In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MultiLabelBinarizer
import pickle

In [2]:
df = pd.read_csv('train_set.csv')
train_Y = np.array(pd.DataFrame(df['Label'])).tolist()
list_1 = []
list_2 = []
for i in train_Y:
    list_2 = [int(i) for i in i[0].split(',')]
    list_1.append(list_2)
Train_Y = MultiLabelBinarizer().fit_transform(list_1)
train_Y = np.asarray(Train_Y.tolist())
train_Y

array([[1, 1, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]])

In [3]:
# adj_matrix表示相关性矩阵，相关矩阵主要是标签a出现时标签b,c,d出现的个数，标签b出现时a,c,d出现的个数这样的…是一个对称矩阵
# nums_matrix保存的则是标签a,b,c,d分别出现的次数
nums_matrix = np.zeros(shape=11)
adj_matrix = np.zeros(shape=(11,11))
adj_matrix,nums_matrix 

(array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [4]:
for index in range(len(train_Y)):
    data = train_Y[index]
    for i in range(11):
        if data[i] == 1:
            nums_matrix[i] += 1
            for j in range(11):
                if j != i:
                    if data[j] == 1:
                        adj_matrix[i][j] += 1

adj = {'adj': adj_matrix,
       'nums': nums_matrix}
adj

{'adj': array([[  0., 472., 286., 126., 456., 259., 165., 256., 257., 324., 309.],
        [472.,   0., 203., 137., 461., 281., 112., 269., 223., 287., 299.],
        [286., 203.,   0.,  67., 233., 152., 145., 139., 240., 225., 187.],
        [126., 137.,  67.,   0., 134.,  98.,  46.,  96.,  73., 117.,  98.],
        [456., 461., 233., 134.,   0., 351., 112., 325., 287., 512., 427.],
        [259., 281., 152.,  98., 351.,   0., 107., 198., 172., 292., 197.],
        [165., 112., 145.,  46., 112., 107.,   0., 124., 131., 150.,  79.],
        [256., 269., 139.,  96., 325., 198., 124.,   0., 201., 268., 184.],
        [257., 223., 240.,  73., 287., 172., 131., 201.,   0., 335., 211.],
        [324., 287., 225., 117., 512., 292., 150., 268., 335.,   0., 225.],
        [309., 299., 187.,  98., 427., 197.,  79., 184., 211., 225.,   0.]]),
 'nums': array([1019.,  681.,  949.,  314., 1299.,  543.,  287.,  855., 1352.,
        1721., 1304.])}

In [5]:
pickle.dump(adj, open('./adj.pkl', 'wb'), pickle.HIGHEST_PROTOCOL)