In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MultiLabelBinarizer
import pickle

In [2]:
df = pd.read_csv('train_set.csv')
train_Y = np.array(pd.DataFrame(df['Label'])).tolist()
list_1 = []
list_2 = []
for i in train_Y:
    list_2 = [int(i) for i in i[0].split(',')]
    list_1.append(list_2)
Train_Y = MultiLabelBinarizer().fit_transform(list_1)
train_Y = np.asarray(Train_Y.tolist())
train_Y

array([[1, 0, 0, ..., 0, 1, 0],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]])

In [3]:
# adj_matrix表示相关性矩阵，相关矩阵主要是标签a出现时标签b,c,d出现的个数，标签b出现时a,c,d出现的个数这样的…是一个对称矩阵
# nums_matrix保存的则是标签a,b,c,d分别出现的次数
nums_matrix = np.zeros(shape=11)
adj_matrix = np.zeros(shape=(11,11))
adj_matrix,nums_matrix 

(array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [4]:
for index in range(len(train_Y)):
    data = train_Y[index]
    for i in range(11):
        if data[i] == 1:
            nums_matrix[i] += 1
            for j in range(11):
                if j != i:
                    if data[j] == 1:
                        adj_matrix[i][j] += 1

adj = {'adj': adj_matrix,
       'nums': nums_matrix}
adj

{'adj': array([[  0., 471., 280., 126., 446., 250., 166., 252., 251., 322., 295.],
        [471.,   0., 199., 135., 449., 266., 111., 263., 213., 275., 284.],
        [280., 199.,   0.,  66., 224., 148., 145., 136., 230., 220., 174.],
        [126., 135.,  66.,   0., 138.,  94.,  44.,  98.,  69., 115.,  96.],
        [446., 449., 224., 138.,   0., 346., 111., 319., 275., 514., 417.],
        [250., 266., 148.,  94., 346.,   0., 105., 190., 165., 289., 183.],
        [166., 111., 145.,  44., 111., 105.,   0., 125., 130., 156.,  73.],
        [252., 263., 136.,  98., 319., 190., 125.,   0., 191., 268., 177.],
        [251., 213., 230.,  69., 275., 165., 130., 191.,   0., 331., 193.],
        [322., 275., 220., 115., 514., 289., 156., 268., 331.,   0., 210.],
        [295., 284., 174.,  96., 417., 183.,  73., 177., 193., 210.,   0.]]),
 'nums': array([1008.,  679.,  946.,  301., 1330.,  538.,  298.,  852., 1327.,
        1705., 1302.])}

In [5]:
pickle.dump(adj, open('./adj.pkl', 'wb'), pickle.HIGHEST_PROTOCOL)