In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MultiLabelBinarizer
import pickle

In [2]:
df = pd.read_csv('train_set.csv')
train_Y = np.array(pd.DataFrame(df['Label'])).tolist()
list_1 = []
list_2 = []
for i in train_Y:
    list_2 = [int(i) for i in i[0].split(',')]
    list_1.append(list_2)
Train_Y = MultiLabelBinarizer().fit_transform(list_1)
train_Y = np.asarray(Train_Y.tolist())
train_Y

array([[1, 1, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]])

In [3]:
# adj_matrix表示相关性矩阵，相关矩阵主要是标签a出现时标签b,c,d出现的个数，标签b出现时a,c,d出现的个数这样的…是一个对称矩阵
# nums_matrix保存的则是标签a,b,c,d分别出现的次数
nums_matrix = np.zeros(shape=11)
adj_matrix = np.zeros(shape=(11,11))
adj_matrix,nums_matrix 

(array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [4]:
for index in range(len(train_Y)):
    data = train_Y[index]
    for i in range(11):
        if data[i] == 1:
            nums_matrix[i] += 1
            for j in range(11):
                if j != i:
                    if data[j] == 1:
                        adj_matrix[i][j] += 1

adj = {'adj': adj_matrix,
       'nums': nums_matrix}
adj

{'adj': array([[  0., 471., 290., 125., 447., 257., 167., 256., 260., 331., 298.],
        [471.,   0., 206., 130., 450., 278., 115., 265., 223., 282., 286.],
        [290., 206.,   0.,  63., 234., 152., 146., 143., 244., 225., 183.],
        [125., 130.,  63.,   0., 126.,  96.,  45.,  99.,  72., 114.,  92.],
        [447., 450., 234., 126.,   0., 347., 116., 321., 288., 508., 413.],
        [257., 278., 152.,  96., 347.,   0., 109., 198., 172., 291., 190.],
        [167., 115., 146.,  45., 116., 109.,   0., 133., 138., 160.,  77.],
        [256., 265., 143.,  99., 321., 198., 133.,   0., 208., 277., 179.],
        [260., 223., 244.,  72., 288., 172., 138., 208.,   0., 348., 207.],
        [331., 282., 225., 114., 508., 291., 160., 277., 348.,   0., 209.],
        [298., 286., 183.,  92., 413., 190.,  77., 179., 207., 209.,   0.]]),
 'nums': array([1021.,  683.,  956.,  309., 1316.,  550.,  297.,  867., 1348.,
        1698., 1313.])}

In [5]:
pickle.dump(adj, open('./adj.pkl', 'wb'), pickle.HIGHEST_PROTOCOL)