In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MultiLabelBinarizer
import pickle

In [2]:
df = pd.read_csv('train_set.csv')
train_Y = np.array(pd.DataFrame(df['Label'])).tolist()
list_1 = []
list_2 = []
for i in train_Y:
    list_2 = [int(i) for i in i[0].split(',')]
    list_1.append(list_2)
Train_Y = MultiLabelBinarizer().fit_transform(list_1)
train_Y = np.asarray(Train_Y.tolist())
train_Y

array([[1, 1, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]])

In [3]:
# adj_matrix表示相关性矩阵，相关矩阵主要是标签a出现时标签b,c,d出现的个数，标签b出现时a,c,d出现的个数这样的…是一个对称矩阵
# nums_matrix保存的则是标签a,b,c,d分别出现的次数
nums_matrix = np.zeros(shape=11)
adj_matrix = np.zeros(shape=(11,11))
adj_matrix,nums_matrix 

(array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [4]:
for index in range(len(train_Y)):
    data = train_Y[index]
    for i in range(11):
        if data[i] == 1:
            nums_matrix[i] += 1
            for j in range(11):
                if j != i:
                    if data[j] == 1:
                        adj_matrix[i][j] += 1

adj = {'adj': adj_matrix,
       'nums': nums_matrix}
adj

{'adj': array([[  0., 463., 285., 127., 443., 251., 164., 248., 262., 330., 303.],
        [463.,   0., 202., 133., 447., 275., 109., 257., 223., 279., 293.],
        [285., 202.,   0.,  65., 230., 147., 143., 137., 238., 226., 188.],
        [127., 133.,  65.,   0., 131.,  97.,  44.,  97.,  70., 115.,  96.],
        [443., 447., 230., 131.,   0., 341., 109., 310., 283., 509., 421.],
        [251., 275., 147.,  97., 341.,   0., 103., 188., 165., 288., 195.],
        [164., 109., 143.,  44., 109., 103.,   0., 123., 127., 150.,  76.],
        [248., 257., 137.,  97., 310., 188., 123.,   0., 201., 267., 172.],
        [262., 223., 238.,  70., 283., 165., 127., 201.,   0., 328., 208.],
        [330., 279., 226., 115., 509., 288., 150., 267., 328.,   0., 218.],
        [303., 293., 188.,  96., 421., 195.,  76., 172., 208., 218.,   0.]]),
 'nums': array([1025.,  675.,  959.,  311., 1302.,  525.,  289.,  843., 1319.,
        1719., 1322.])}

In [5]:
pickle.dump(adj, open('./adj.pkl', 'wb'), pickle.HIGHEST_PROTOCOL)