In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MultiLabelBinarizer
import pickle

In [2]:
df = pd.read_csv('train_set.csv')
train_Y = np.array(pd.DataFrame(df['Label'])).tolist()
list_1 = []
list_2 = []
for i in train_Y:
    list_2 = [int(i) for i in i[0].split(',')]
    list_1.append(list_2)
Train_Y = MultiLabelBinarizer().fit_transform(list_1)
train_Y = np.asarray(Train_Y.tolist())
train_Y

array([[1, 1, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]])

In [3]:
# adj_matrix表示相关性矩阵，相关矩阵主要是标签a出现时标签b,c,d出现的个数，标签b出现时a,c,d出现的个数这样的…是一个对称矩阵
# nums_matrix保存的则是标签a,b,c,d分别出现的次数
nums_matrix = np.zeros(shape=11)
adj_matrix = np.zeros(shape=(11,11))
adj_matrix,nums_matrix 

(array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

In [4]:
for index in range(len(train_Y)):
    data = train_Y[index]
    for i in range(11):
        if data[i] == 1:
            nums_matrix[i] += 1
            for j in range(11):
                if j != i:
                    if data[j] == 1:
                        adj_matrix[i][j] += 1

adj = {'adj': adj_matrix,
       'nums': nums_matrix}
adj

{'adj': array([[  0., 472., 288., 124., 443., 257., 160., 249., 262., 337., 303.],
        [472.,   0., 205., 124., 447., 275., 107., 256., 221., 277., 293.],
        [288., 205.,   0.,  64., 228., 153., 151., 137., 245., 236., 186.],
        [124., 124.,  64.,   0., 122.,  96.,  42.,  95.,  69., 113.,  89.],
        [443., 447., 228., 122.,   0., 337., 111., 312., 286., 509., 419.],
        [257., 275., 153.,  96., 337.,   0., 105., 187., 170., 285., 195.],
        [160., 107., 151.,  42., 111., 105.,   0., 125., 136., 160.,  76.],
        [249., 256., 137.,  95., 312., 187., 125.,   0., 203., 268., 177.],
        [262., 221., 245.,  69., 286., 170., 136., 203.,   0., 344., 209.],
        [337., 277., 236., 113., 509., 285., 160., 268., 344.,   0., 220.],
        [303., 293., 186.,  89., 419., 195.,  76., 177., 209., 220.,   0.]]),
 'nums': array([1018.,  672.,  977.,  303., 1300.,  534.,  294.,  848., 1329.,
        1732., 1304.])}

In [5]:
pickle.dump(adj, open('./adj.pkl', 'wb'), pickle.HIGHEST_PROTOCOL)